services:
  postgres:
    container_name: 'postgres-emu-fs'
    image: 'postgres:15.5'
    environment:
      - 'POSTGRES_DB=filesystem'
      - 'POSTGRES_PASSWORD=Dam*@*Szb7Vzy$4VFi'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data'
    volumes:
      - 'postgres:/data/postgres'
    ports:
      - '32768:5432'
    networks:
      - 'backend-network'
    restart: unless-stopped

  maildev:
    container_name: 'maildev-emu-fs'
    image: 'maildev/maildev'
    ports:
      - '1080:1080'
      - '1025:1025'

networks:
  backend-network:
    driver: bridge

volumes:
  postgres:
    driver: local