CREATE SEQUENCE IF NOT EXISTS otp_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE otp
(
    id         INTEGER NOT NULL,
    otp        VARCHAR(12),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT  NOT NULL,
    CONSTRAINT pk_otp PRIMARY KEY (id)
);

ALTER TABLE otp
    ADD CONSTRAINT FK_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES _user (id);
